finnlabs/openproject-my_project_page

- app/views/my_projects_overviews/_block_textilizable.html.erb
- app/views/my_projects_overviews/blocks/_members.html.erb
- app/views/my_projects_overviews/blocks/_news_latest.html.erb
- app/views/my_projects_overviews/blocks/_work_package_tracking.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_assigned_to_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_reported_by_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_responsible_for.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_watched.html.erb
- app/views/my_projects_overviews/page_layout.html.erb
- app/views/my_projects_overviews/password.html.erb
:warning: **Depends on opf/openproject#2294. Please review, merge first.**
https://community.openproject.org/work_packages/17751
> Initial update for Foundation for Apps integration

- app/assets/javascripts/my_project_page/my_project_page.js
- app/views/my_projects_overviews/_block.html.erb
- app/views/my_projects_overviews/page_layout.html.erb
- app/views/my_projects_overviews/remove_block.js.erb
- features/step_definitions/block_steps.rb
This PR fixes the failing cukes for this plugin on our internal CI. This was documented by @NobodysNightmare and relates to https://community.openproject.org/work_packages/19871.
:warning:__This PR depends on changes made in https://github.com/opf/openproject/pull/2982!__ :warning:
> [19871] Fix Failing cukes on internal CI

- app/views/my_projects_overviews/index.html.erb
- app/views/my_projects_overviews/page_layout.html.erb
- app/views/my_projects_overviews/password.html.erb
This will make use of the toolbar component in this plugin.
:warning: __This depends on opf/openproject#3000__ Review first! :warning:
> [18330] use toolbar component in the plugin

- app/assets/javascripts/my_project_page/my_project_page.js
- app/views/my_projects_overviews/index.html.erb
this should fix a failing cuke which was a poistive test for missing functionality which broke due to changing the block ids.
> Fix locking of used blocks in select menu

- app/views/my_projects_overviews/_block_textilizable.html.erb
- app/views/my_projects_overviews/password.html.erb
[``* `#19842` Apply new button styling in openproject-my_project_page``](https://community.openproject.org/work_packages/19842)
> 19842 apply new button styles

- app/controllers/my_projects_overviews_controller.rb
- app/models/my_projects_overview.rb
:information_source: **Please see finnlabs/openproject-backlogs#145 for explanation.**
> [Rails4] fix constant reloading issues: remove unloadable

- config/locales/en.yml
https://community.openproject.org/work_packages/20979
> Removes unused string

- app/views/my_projects_overviews/blocks/_project_details.html.erb
- config/locales/da.yml
- config/locales/de.yml
- config/locales/en.yml
- config/locales/es-ES.yml
- config/locales/fr.yml
- config/locales/it.yml
- config/locales/lv.yml
- config/locales/pl.yml
- config/locales/pt-BR.yml
- config/locales/sv-SE.yml
- config/locales/tr.yml
:warning: This PR removes the homepage field of projects :warning: 
This belongs to https://github.com/opf/openproject/pull/3422
https://community.openproject.org/work_packages/1928
> Remove project homepage field

- app/controllers/my_projects_overviews_controller.rb
- app/views/my_projects_overviews/blocks/_spent_time.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_assigned_to_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_reported_by_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_responsible_for.html.erb
- features/step_definitions/selected_widgets_steps.rb
- openproject-my_project_page.gemspec
- spec/models/my_projects_overview_spec.rb
:warning: **Please review, merge opf/openproject#3382 first.**
https://community.openproject.org/work_packages/20043
> [20043] Upgrade to Rails 4.1.x

- db/migrate/20130903172842_my_project_page_migrate_serialized_yaml.rb
https://github.com/opf/openproject/pull/3459
> Use LegacyYamler for migration from syck

- app/views/my_projects_overviews/_textilizable.html.erb
set headline to h3 and assigned the wiki class, like the other boxes on the page
https://community.openproject.org/work_packages/20782
> [20782] Unify widget headings

- app/views/my_projects_overviews/blocks/_spent_time.html.erb
Doesn't really have a ticket I guess. Maybe @RobinWagner knows one.
> Fix include statement

- openproject-my_project_page.gemspec
:warning: **Includes commits from Rails 4.2.x PR. Please review, merge first.**
:warning: **Please review, merge opf/openproject#3421 first.**
https://community.openproject.org/work_packages/20044
> [20044] Upgrade to Rails 4.2.x

- app/views/my_projects_overviews/blocks/_calendar.html.erb
https://community.openproject.org/work_packages/21646/activity
> Fix deprecated finder method in calendar block

- app/views/my_projects_overviews/blocks/_spent_time.html.erb
This PR applies the new table component style for the table 'spent time' on myProjectPage.
https://community.openproject.org/work_packages/21667/activity
> [21667] Apply new table styling on my-project-page

- app/assets/javascripts/my_project_page/my_project_page.js
- app/assets/stylesheets/my_project_page/my_projects_overview.sass
- app/views/my_projects_overviews/_block.html.erb
- app/views/my_projects_overviews/_block_textilizable.html.erb
- app/views/my_projects_overviews/_textilizable.html.erb
- app/views/my_projects_overviews/blocks/_calendar.html.erb
- app/views/my_projects_overviews/blocks/_members.html.erb
- app/views/my_projects_overviews/blocks/_news_latest.html.erb
- app/views/my_projects_overviews/blocks/_project_description.html.erb
- app/views/my_projects_overviews/blocks/_project_details.html.erb
- app/views/my_projects_overviews/blocks/_spent_time.html.erb
- app/views/my_projects_overviews/blocks/_subprojects.html.erb
- app/views/my_projects_overviews/blocks/_work_package_tracking.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_assigned_to_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_reported_by_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_responsible_for.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_watched.html.erb
- app/views/my_projects_overviews/index.html.erb
- app/views/my_projects_overviews/page_layout.html.erb
- features/project_details_widget.feature
- features/step_definitions/custom_overview_page_steps.rb
- features/subprojects_widget.feature
https://community.openproject.org/work_packages/21862/activity
As we're using the dragula plugin for drag and drop on my_page, we should use this also here.
@why-el will take care of this.
> [21862] Apply widget-box styles

- app/views/my_projects_overviews/index.html.erb
https://community.openproject.org/work_packages/21863/activity
> [21863] Add project-overview class for correct alignment

- app/views/my_projects_overviews/_block_textilizable.html.erb
- app/views/my_projects_overviews/blocks/_work_package_tracking.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_assigned_to_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_reported_by_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_responsible_for.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_watched.html.erb
- app/views/my_projects_overviews/password.html.erb
This applies the new icon styling in the plugin. Note that this only works in combination with https://github.com/opf/openproject/pull/3873 since there the icon font is updated.
https://community.openproject.org/work_packages/22106/activity
> [22106] Apply new icon styling (My Project Page)

- app/views/my_projects_overviews/blocks/_members.html.erb
> Fix removed members path

- .travis.yml
- app/controllers/my_projects_overviews_controller.rb
- app/views/my_projects_overviews/blocks/_members.html.erb
- config/routes.rb
- lib/open_project/my_project_page/engine.rb
Fixes https://community.openproject.com/projects/openproject/work_packages/24160
> [24160] 	Replace the member button with a redirect to the members page

- app/controllers/my_projects_overviews_controller.rb
- spec/controllers/my_projects_overview_controller_spec.rb
This changes the redirection page after submit to the index page.
https://community.openproject.com/work_packages/24292/activity
> [24292] Save button on project overview does not close edit mode

- .travis.yml
- app/views/my_projects_overviews/_block.html.erb
- app/views/my_projects_overviews/_block_textilizable.html.erb
- app/views/my_projects_overviews/blocks/_project_description.html.erb
- spec/features/block_editing_spec.rb
https://community.openproject.com/work_packages/24356
> [24356] 	Fix edit permissions on overview edit page

- frontend/app/components/projects-overview/overview-block.directive.ts
- frontend/app/components/projects-overview/overview-page-layout.directive.ts
- frontend/app/components/projects-overview/overview-textile-block.directive.ts
https://github.com/opf/openproject/pull/5192
> Adapt to stricter core

- app/views/my_projects_overviews/blocks/_spent_time.html.erb
https://github.com/opf/openproject/pull/5213
> Apply sticky header

- app/views/my_projects_overviews/blocks/_calendar.html.erb
- app/views/my_projects_overviews/blocks/_members.html.erb
- app/views/my_projects_overviews/blocks/_news_latest.html.erb
- app/views/my_projects_overviews/blocks/_project_description.html.erb
- app/views/my_projects_overviews/blocks/_spent_time.html.erb
- app/views/my_projects_overviews/blocks/_work_package_tracking.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_assigned_to_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_reported_by_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_responsible_for.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_watched.html.erb
- app/views/my_projects_overviews/index.html.erb
https://github.com/opf/openproject/pull/5423
> Icon accessibility [belongs to #5423]

- app/views/my_projects_overviews/blocks/_members.html.erb
- app/views/my_projects_overviews/blocks/_news_latest.html.erb
- app/views/my_projects_overviews/blocks/_work_package_tracking.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_assigned_to_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_reported_by_me.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_responsible_for.html.erb
- app/views/my_projects_overviews/blocks/_work_packages_watched.html.erb
Apply inverted class for buttons. Closely related to: https://github.com/opf/openproject/pull/6098
https://community.openproject.com/projects/gmbh/work_packages/25659/activity
> [25659] Buttons with inverted color scheme (MyProjectPage)

- frontend/legacy-app/components/projects-overview/overview-page-layout.directive.ts
- frontend/legacy-app/components/projects-overview/overview-textile-block.directive.ts
- spec/features/block_editing_spec.rb
https://github.com/opf/openproject/pull/6450
> Allow dynamic insertion of ckeditor

- app/views/my_projects_overviews/_block_textilizable.html.erb
https://github.com/opf/openproject/pull/6485
> use helper for attachments list

- app/assets/stylesheets/my_project_page/my_projects_overview.sass
- app/views/my_projects_overviews/_block_textilizable.html.erb
- spec/features/block_editing_spec.rb
https://community.openproject.com/wp/28399
> [28399] Fix embedded table editing

- config/locales/en.seeders.yml
Add link in demo data to start the guided tour
https://github.com/opf/openproject/pull/6743
https://community.openproject.com/projects/openproject/work_packages/28535/activity
> [27586] Guided tour for user onboarding (MyProjectPage)
